### ISSUE TITLE
Can't handle requestBody defined by $ref

### ISSUE THREAD

**Issue by DougReeder** [ninofiliu/oa-client#3]
When attempting to use an endpoint defined as 
```yaml
    patch:
      summary: partial update user
      tags: [Users]
      operationId: updateUserPartial
      'x-type': 'passthru-patch'
      requestBody:
        $ref: '#/components/requestBodies/User'
      responses:
        '200':
          $ref: '#/components/responses/User'
        '403':
          $ref: '#/components/responses/Forbidden'
        '4XX':
          $ref: '#/components/responses/BadRequest'
        '5XX':
          $ref: '#/components/responses/ServerError'
```
throws the error:
```
(node:62889) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'application/json' of undefined
    at _default (.../node_modules/oa-client/dist/create-client/validate-request/validate-body.js:29:27)
    at _default (.../node_modules/oa-client/dist/create-client/validate-request/index.js:44:31)
    at Object.put (.../server/node_modules/oa-client/dist/create-client/index.js:36:34)
    at Object.updateUserComplete (.../handlers/users.js:72:44)
 ```
because requestBody does not contain a `content` field.

**Comment by ninofiliu** [comment]
Thanks for raising this issue! I'll look into it this week

**Comment by ninofiliu** [comment]
Oh I see. To be clear, `oa-client` ***does not*** resolve $refs. You have to resolve them yourself, for example with [json-schema-ref-parser](https://www.npmjs.com/package/@apidevtools/json-schema-ref-parser). `oa-client` only handles resolved OpenAPI specs.

**Comment by DougReeder** [comment]
Ok! This should probably be documented in the README.

**Comment by ninofiliu** [comment]
You're right, thx for the suggestion! https://github.com/ninofiliu/oa-client/commit/177d1ffca8bc8ba93764b0fcefe66d7346236fea
